### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by Keruspe** [redirectionio/redirection.io-exheres#1]
# repository
- You don't use any exlib from rust or net so they shouldn't be i your masters
- Why do you need `PALUDIS_DO_NOTHING_SANDBOXY=1`?

# all packages
- We usually don't do revisions such as -r1 for scm packages, you should just leave the version as raw "scm"
- HOMEPAGE is already set by github.exlib
- instead of calling autoreconf, you should use the autotools exlib

# libredirectionio
- `require github` with just the user param should be sufficient
- rust is slotted, so the dependency should probably be `dev-lang/rust:*`

# agent
- as there is no build, dependencies should only be run dependencies
- use keepdir
- use insinto, doins, exeinto, doexe

**Comment by joelwurtz** [comment]
Everything has been fixed by the last commits, thanks for your review, it's really helping us doing things right as we are discovering exherbo.

> Why do you need PALUDIS_DO_NOTHING_SANDBOXY=1?

This is in our Dockerfile and it's required to make cave works, don't really know why, this is something that i have seen on some docker images for exherbo. But i removed (mainly moved in fact) our Dockerfile from this repo as it's not needed.
